#!/usr/bin/env bash

set -euo pipefail

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SQL_DIR="$SCRIPT_DIR/../migrations"
OUTPUT_FILE="$SCRIPT_DIR/../packages/pgconductor-js/src/generated/sql.ts"
VERSION_FILE="$SCRIPT_DIR/../packages/pgconductor-js/src/version.ts"

# Start building the TypeScript module
echo "/* This file is auto-generated by \`just build-migrations\`; DO NOT EDIT */" > "$OUTPUT_FILE"
echo "export const getMigrations = (schemaName: string) => ({" >> "$OUTPUT_FILE"

latest_version=""

# Find all SQL files matching the pattern (10 digits + underscore + name) and sort them
for file in "$SQL_DIR"/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_*.sql; do
    [ -e "$file" ] || continue

    filename=$(basename "$file")
    # Extract the version (first 10 digits)
    version="${filename:0:10}"
    latest_version="$version"

    # Read SQL content - use String.raw to avoid escape sequence interpretation
    # Process with awk to handle backticks and schema placeholders
    echo "  \"$filename\": String.raw\`" >> "$OUTPUT_FILE"
    cat "$file" | awk '
        {
            # Escape backticks for template literal
            gsub(/`/, "\\`")
            # Replace {{schema_name}} with ${schemaName} for template literal interpolation
            gsub(/\{\{schema_name\}\}/, "${schemaName}")
            print
        }
    ' >> "$OUTPUT_FILE"
    echo "\`," >> "$OUTPUT_FILE"
done

echo "});" >> "$OUTPUT_FILE"

# Write the latest migration version to version.ts as a number
if [ -n "$latest_version" ]; then
    echo "/* This file is auto-generated by \`just build-migrations\`; DO NOT EDIT */" > "$VERSION_FILE"
    echo "export const VERSION = $latest_version;" >> "$VERSION_FILE"
fi
